### ISSUE TITLE
Composer/Packagist: no css for all themes for phpmyadmin 5.0.0

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/scripts#21]
### Describe the bug

CSS folders for all themes are empty after loading project via [composer](https://packagist.org/packages/phpmyadmin/phpmyadmin).
`composer clearcache` does not help.

### To Reproduce

1. `composer create-project phpmyadmin/phpmyadmin --no-dev`
2. **themes/metro/css**, **themes/original/css** and **themes/pmahomme/css** folders are empty

### Server configuration

- Operating system: Ubuntu 18.04.3 LTS
- Web server: Apache 2.4
- PHP version: PHP 7.3.13
- phpMyAdmin version: 5.0.0

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/scripts/blob/8b500ea383289f7a0f5812578fdff2f9b33bf583/website/daily-composer#L112

I think we could add the CSS generation here

**Comment by williamdes** [comment]
Thank you for the report @Jay04653

**Comment by williamdes** [comment]
I added the following lines on my local script
```
yarn
git add --force themes/*/css/*.css
git add --force themes/*/css/*.css.map
```

**Comment by ibennetch** [comment]
I believe I have fixed this, please reopen the issue if you still have this problem.

Thank you for reporting it!

**Comment by Jay04653** [comment]
Yes, it's working now, thank you!
