### ISSUE TITLE
https://reports.phpmyadmin.net/ is down

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/scripts#24]
https://reports.phpmyadmin.net/ = 502

**Comment by ibennetch** [comment]
I'm working on this, thanks.

**Comment by ibennetch** [comment]
I believe this is now fixed, please let me know if there are further problems.

During a recent system upgrade, I neglected to properly allocate the fpm pool for this resource.

**Comment by williamdes** [comment]
Thank you :)
