### ISSUE TITLE
phpmyadmin.net is not accessible via IPv6

### ISSUE THREAD

**Issue by miyurusankalpa** [phpmyadmin/scripts#36]
Cannot download phpmyadmin on a IPv6 only server.

both www.phpmyadmin.net and files.phpmyadmin.net does not have AAAA records.

`Connecting to files.phpmyadmin.net (files.phpmyadmin.net)|185.93.2.15|:443... failed: Connection timed out.
`
`Connecting to www.phpmyadmin.net (www.phpmyadmin.net)|195.181.174.2|:443... failed: Connection timed out.`

phpmyadmin.net does have a AAAA record but, connections are refused.

`Connecting to phpmyadmin.net (phpmyadmin.net)|2a01:4f8:13b:15a3::2|:443... failed: Connection refused.`

### Describe the solution you'd like

1. Fix the connection issue (probably only binded to IPv4 or firewall block) and  add AAAA to www subdomain as well.

2. Since files.phpmyadmin.net uses CDN77 as the CDN, I have contacted them asking about IPv6 connectivity. ~I will update this post once they reply.~ Got a reply, they dont support IPv6 yet.

**Comment by williamdes** [comment]
I moved this issue here to clean out all pure infrastructure tasks from out main repository and added a [infrastructure label](https://github.com/phpmyadmin/scripts/labels/infrastructure) to have them in one group.

**Comment by miyurusankalpa** [comment]
It works now. Thanks @ibennetch.

```
miyuru@MIYURU-LAP:/tmp$ wget https://phpmyadmin.net
--2020-10-18 12:07:10--  https://phpmyadmin.net/
Resolving phpmyadmin.net (phpmyadmin.net)... 2a01:4f8:13b:15a3:1::10, 94.130.222.149
Connecting to phpmyadmin.net (phpmyadmin.net)|2a01:4f8:13b:15a3:1::10|:443... connected.
```

I will be closing this issue now as the primary issue is fixed and the other problems are related to CDN77.

**Comment by TomHetmer** [comment]
Hey all,

we are rolling out v6 on all CDN77 accounts, right now there is a small beta test in Frankfurt.
We should be fully IPv6 ready in the next few months.

Also, by the way, we're running a DoT test with 1.1.1.1 on files.phpmyadmin.net - all requests from their resolver for this domain are encrypted on the wire.

**Comment by ibennetch** [comment]
That's great news, @TomHetmer.

We are so happy with our partnership with and support from CDN77, thank you.

**Comment by TomHetmer** [comment]
Merry Christmas, phpMyAdmin🎄 

# dig files.phpmyadmin.net aaaa +short
1560827080.rsc.cdn77.org.
2a02:6ea0:c207::17
2a02:6ea0:c207::16

**Comment by williamdes** [comment]
Thank you !! :rocket: 
re-opening for @ibennetch to restore the website record that was modified

**Comment by ibennetch** [comment]
This should all work correctly. Traffic from IPv4 or IPv6 to https://phpmyadmin.net gets redirected to https://www.phpmyadmin.net which is handled through the CDN. Everything should be correct.

@TomHetmer Thank you again, we appreciate it!
