### ISSUE TITLE
Docker edge- tags are not building

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/scripts#42]
The cli sends trigger requests, are they received ?

![image](https://user-images.githubusercontent.com/7784660/112301787-97872200-8c9a-11eb-89f4-57f7c5065444.png)

**Comment by ibennetch** [comment]
I’m pretty sure we stopped offering edge builds quite some time ago. I’ll
have to look for the ticket or commit for it, but it was quite a bit of
overhead to keep maintaining something that was not being used much.

We certainly no longer advertise it in the “Supported tags” section of
https://hub.docker.com/_/phpmyadmin

**Comment by williamdes** [comment]
We should remove all the code in scripts that does triggers to Docker hub then 🤔

**Comment by williamdes** [comment]
Edge tags should be deleted from the Hub

**Comment by ibennetch** [comment]
Done — they're deleted from
https://hub.docker.com/repository/docker/phpmyadmin/phpmyadmin/tags

Thanks!

**Comment by williamdes** [comment]
We should probably revoke the secret used to trigger them and remove the code from the website
