### ISSUE TITLE
Composer/Packagist: 5.1.2 version missing

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/scripts#45]
Could you please check/fix the automatic build flow?

**Comment by williamdes** [comment]
I received emails and it says at the end
```
scripts/website/daily-composer: 1: scripts/website/daily-composer: Syntax error: Unterminated quoted string
```

Some fix may be needed

**Comment by ibennetch** [comment]
Thanks, this should now be fixed. There was a commit that caused the tag processing to break which has now been resolved.

**Comment by williamdes** [comment]
Ref: a5636204a44af6ee641a965617609788c4653cda

**Comment by ibennetch** [comment]
a563620 had a missing quote because of a bad copy and paste, but I reverted that and dde539fdbd12b029aace1f3a173e4bc5fadd7642 also had not escaped the braces, so we've had two problematic commits lately :)
