### ISSUE TITLE
Daily composer is failing

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/scripts#48]
The daily composer build generated by `scripts/website/daily-composer` is failing. The last few lines are:

```
js/dist/u2f.js.map
error: pathspec 'js/dist/ajax.js.map' did not match any file(s) known to git
error: pathspec 'js/dist/chart.js.map' did not match any file(s) known to git
error: pathspec 'js/dist/codemirror/addon/lint/sql-lint.js.map' did not match any file(s) known to git
error: pathspec 'js/dist/common.js.map' did not match any file(s) known to git
error: pathspec 'js/dist/config.js.map' did not match any file(s) known to git
error: pathspec 'js/dist/console.js.map' did not match any file(s) known to git
and many more
```

**Comment by williamdes** [comment]
It should not output this anymore since 30c8b4211d7ecb21fdb6607cc701e9f2af881ff5
To be monitored

**Comment by liviuconcioiu** [comment]
It seems the snapshots aren't generated anymore, for both versions.

**Comment by ibennetch** [comment]
> It seems the snapshots aren't generated anymore, for both versions.

I've opened https://github.com/phpmyadmin/phpmyadmin/issues/18109 about the cause of that.

**Comment by williamdes** [comment]
Daily composer ran without any issues: https://github.com/phpmyadmin/composer/tree/5.2.x
