### ISSUE TITLE
Leak of security issue title in "Handled issues"

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/scripts#9]
in:
https://blog.cihar.com/archives/2016/12/27/weekly-phpmyadmin-contributions-2016-w51/
```
#133 Session puzzling https://github.com/phpmyadmin/phpmyadmin-security/issues/133
```
issues from phpmyadmin-security need to be stripped when phpmyadmin-reports script is used:
https://github.com/phpmyadmin/scripts/blob/master/phpmyadmin-reports#L46-L49

**Comment by nijel** [comment]
This filtering was done manually so far and obviously I've missed this one. The tool should be able to generate both reports as it's used for monthly work reports as well which are not public, but should cover all handled issues.
